# Generated by Django 5.2.10 on 2026-02-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_manager', '0007_bilyonerbulletin_match_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Yatırılan Tutar')),
                ('total_odds', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Toplam Oran')),
                ('potential_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Olası Kazanç')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('WON', 'Tuttu'), ('LOST', 'Yattı')], default='PENDING', max_length=10, verbose_name='Durum')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.CharField(blank=True, max_length=50)),
                ('match_time', models.CharField(blank=True, max_length=50)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='TURKEY', max_length=50)),
                ('prediction', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('WON', 'Tuttu'), ('LOST', 'Yattı')], default='PENDING', max_length=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='betting_engine.coupon')),
                ('match', models.ForeignKey(blank=True, help_text='Reference to bulletin if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.bilyonerbulletin')),
            ],
        ),
    ]
