# Generated by Django 5.2.10 on 2026-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='Güven Oranı (%)'),
        ),
    ]
