# Generated by Django 5.2.10 on 2026-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0002_coupon_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_played',
            field=models.BooleanField(default=False, verbose_name='Oynandı mı?'),
        ),
    ]
