# Generated by Django 5.2.10 on 2026-02-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0003_coupon_is_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilyonerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='TC Kimlik / Üye No')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
