# Generated by Django 5.2.10 on 2026-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0004_bilyonercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arşivlendi mi?'),
        ),
    ]
