# Generated by Django 5.2.10 on 2026-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0005_coupon_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='execution_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Bot İşlem Durumu'),
        ),
    ]
