# Generated by Django 5.2.10 on 2026-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField(default=0)),
                ('player_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
