# Generated by Django 5.2.10 on 2026-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_turkeyfixture_turkeystanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya')], default='TURKEY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('away_team', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['country', 'week'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya')], default='TURKEY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField(default=0)),
                ('player_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('matches_played', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya')], default='TURKEY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=100)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['country', 'rank'],
            },
        ),
        migrations.DeleteModel(
            name='SquadPlayer',
        ),
        migrations.DeleteModel(
            name='TurkeyFixture',
        ),
        migrations.DeleteModel(
            name='TurkeyStanding',
        ),
    ]
