# Generated by Django 5.2.10 on 2026-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_fixture_player_standing_delete_squadplayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
