# Generated by Django 5.2.10 on 2026-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_player_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilyonerBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya'), ('GERMANY', 'Almanya')], default='TURKEY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_key', models.CharField(max_length=255, unique=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('match_time', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('ms_1', models.CharField(default='-', max_length=10)),
                ('ms_x', models.CharField(default='-', max_length=10)),
                ('ms_2', models.CharField(default='-', max_length=10)),
                ('under_2_5', models.CharField(default='-', max_length=10)),
                ('over_2_5', models.CharField(default='-', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Bilyoner Bulletins',
                'ordering': ['country', 'match_time'],
            },
        ),
        migrations.AlterField(
            model_name='fixture',
            name='country',
            field=models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya'), ('GERMANY', 'Almanya')], default='TURKEY', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya'), ('GERMANY', 'Almanya')], default='TURKEY', max_length=20),
        ),
        migrations.AlterField(
            model_name='standing',
            name='country',
            field=models.CharField(choices=[('TURKEY', 'Türkiye'), ('ENGLAND', 'İngiltere'), ('SPAIN', 'İspanya'), ('ITALY', 'İtalya'), ('GERMANY', 'Almanya')], default='TURKEY', max_length=20),
        ),
    ]
