# Generated by Django 5.2.10 on 2026-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_bilyonerbulletinstaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilyonerbulletin',
            name='match_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bilyonerbulletinstaging',
            name='match_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
