# Generated by Django 5.2.10 on 2026-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_bilyonerbulletin_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilyonerbulletin',
            name='gemini_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Gemini AI Analizi'),
        ),
    ]
