# Generated by Django 5.2.10 on 2026-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='Actual source code of the function'),
        ),
    ]
